apiVersion: v1
kind: Service
metadata:
  name: app
  labels: app
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app
  labels:
    service: app
spec:
  replicas: 2
  selector:
    matchLabels:
      service: app
  strategy:
    type: RollingUpdate
    RollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        service: app
    spec:
      containers:
      - image: https://303036157700.dkr.ecr.eu-central-1.amazonaws.com/samsara:latest
        name: app
        ports:
          - protocol: TCP
            containerPort: 9000
            name: app