apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    service: app-service
spec:
  replicas: 2
  selector:
    matchLabels:
      service: app-service
      app: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: app-service
        app: app
    spec:
      containers:
      - image: https://303036157700.dkr.ecr.eu-central-1.amazonaws.com/samsara:latest
        name: app
        ports:
          - protocol: TCP
            containerPort: 9000