apiVersion: v1
kind: Service
metadata:
  name: db
  labels: db
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db
  labels:
    service: db
spec:
  replicas: 2
  type: LoadBalancer
  selector:
    matchLabels:
      service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: db
    spec:
      containers:
      - image: https://303036157700.dkr.ecr.eu-central-1.amazonaws.com/db:db:latest
        name: db
        ports:
          - protocol: TCP
            containerPort: 5432
            name: db