apiVersion: v1
kind: Service
metadata:
  labels: db-service
  name: db-service
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  type: LoadBalancer
  selector:
    name: app
    app: app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: db-service
  name: db-deployment
spec:
  selector:
    matchLabels:
      service: db-service
      app: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: db-service
        app: app
    spec:
      containers:
      - image: 303036157700.dkr.ecr.eu-central-1.amazonaws.com/db:latest
        name: db
        ports:
          - protocol: TCP
            containerPort: 5432