apiVersion: v1
kind: Service
metadata:
  labels:
    run: db
  name: db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    run: db
  type: LoadBalancer
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: db
  name: db
spec:
  replicas: 2
  selector:
    matchLabels:
      service: db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: db
    spec:
      containers:
      - image: 303036157700.dkr.ecr.eu-central-1.amazonaws.com/db:latest
        name: db
        ports:
          - protocol: TCP
            containerPort: 5432